### ISSUE TITLE
Preload-Images.sh failing when "/" in name

### ISSUE THREAD

**Issue by rmsapp** [aws-samples/aws-snow-tools-for-eks-anywhere#19]
When executing the ./build.sh script, we are getting the following error in 

> Using latest Snow AL2 AMI ami-02d3a19e13471e0bd to create local registry AMI
Preloading images on images.txt
latest: Pulling from library/mongo
Digest: sha256:bf1d25bae7c2fd47cd9a89eec3db08e73ccfbef666e43f583fa6b560ca07ac5a
Status: Image is up to date for mongo:latest
docker.io/library/mongo:latest
latest: Pulling from library/nginx
Digest: sha256:08bc36ad52474e528cc1ea3426b5e3f4bad8a130318e3140d6cfe29c8892c7ef
Status: Image is up to date for nginx:latest
docker.io/library/nginx:latest
latest: Pulling from bitnami/kafka
4c126e3eebe3: Pull complete
Digest: sha256:22f7f16a9edb40a49990a48f993993296ff617f6d41feec913c95d36a697def9
Status: Downloaded newer image for bitnami/kafka:latest
docker.io/bitnami/kafka:latest
**./preload-images.sh: line 15: images/bitnami/kafka:latest.tar: No such file or directory**

The images.txt file looks like this:

> mongo:latest
nginx:latest
bitnami/kafka:latest

All of the images pull fine, however when there is a "/" in the name of any image we are pulling, the preload-images.sh script fails to find it.  We tried with other images that have a path prior to the name as well.

**Comment by yxinchen** [comment]
Fixed with PR: https://github.com/aws-samples/aws-snow-tools-for-eks-anywhere/pull/20
