### ISSUE TITLE
Support to run This script in Mac 

### ISSUE THREAD

**Issue by kakarotbyte** [aws-samples/aws-snow-tools-for-eks-anywhere#21]
I tried to create this scripts in MAC and the credentials file it created has `-e` in it. Similarly other shell scripts also have issue with Mac. Please add support for running these scripts on other OS as well.

https://github.com/aws-samples/aws-snow-tools-for-eks-anywhere/tree/266aca031d86ca024084cb20e51bdfd1da549c4e/setup-tools

**Comment by yxinchen** [comment]
example problematic credentials file generated on mac
```
snowball_creds
-e [10.80.26.21]
aws_access_key_id = <access key id>
aws_secret_access_key = <secret key>
region = snow
```
A good credentials file should be 
```
[10.80.26.21]
aws_access_key_id = <access key id>
aws_secret_access_key = <secret key>
region = snow
```

**Comment by yxinchen** [comment]
fixed with pr https://github.com/aws-samples/aws-snow-tools-for-eks-anywhere/pull/22
